=== TERITORI/teritori-dapp/cosmwasm-contracts/cw721-membership/schema/raw/instantiate.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "InstantiateMsg",
  "type": "object",
  "required": [
    "admin_addr",
    "description",
    "image_uri",
    "mint_royalties",
    "name",
    "symbol"
  ],
  "properties": {
    "admin_addr": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "image_uri": {
      "type": "string"
    },
    "mint_royalties": {
      "type": "integer",
      "format": "uint16",
      "minimum": 0.0
    },
    "name": {
      "type": "string"
    },
    "symbol": {
      "type": "string"
    }
  }
}

=== TERITORI/teritori-dapp/cosmwasm-contracts/cw721-membership/config.json
{
  "admin_addr": "__ADMIN_ADDR__",
  "mint_royalties": 500,
  "name": "Premium Memberships",
  "description": "Premium Memberships are exclusively held by premium subscribers of content creators, offering them access to content specially reserved for the creators' communities.\n\nBy holding a Premium Membership from a creator, you:\n\n- Directly support the creation of their unique content.\n- Gain privileged access to their latest creations.\n- Receive access to exclusive perks as defined by the creator.\n- Contribute to the broader economy of Teritori OS, with fees being reinvested into the $TORI token.\n- Play a crucial role in the development of the Teritori ecosystem, aiding in financing the sustainable resilience of future communities.\n- Enjoy potential future benefits across all Teritori OS features, including whitelists, airdrops, early access to new features, alpha information, and more.\n\nEmbrace the opportunity to be part of a vibrant creator economy while enjoying exclusive content and perks designed to enrich your experience.",
  "symbol": "PMEM",
  "image_uri": "ipfs://bafybeiaznarsgwk7stav6qrzjnwqw4j7eu7drm3xx4p3fokgsnrouelse4"
}
